### ISSUE TITLE
Flag stack traces that don't result in the service dying

### ISSUE THREAD

**Issue by laurenassour** [aquanauts/alogamous#6]
In our logs this is easy because we have a 'starting' header that makes it obvious when a service starts up, at least. We want to see if we're dumping stack traces that are going unnoticed.

**Comment by kitrady** [comment]
What is a stack trace? What is dumping a stack trace and why would it going unnoticed be a problem?

**Comment by benrady** [comment]
Great question! "Stack trace" is a generic name...Python calls these "Tracebacks" for some reason.

https://stackoverflow.com/questions/1508467/log-exception-with-traceback-in-python

**Comment by benrady** [comment]
Basically, it's something you can write to the log file that says an error occurred, what the error was, and what lines of code were involved in the error. It prints out the entire call stack (function A, calls function B, calls function C, etc...). Hence the name "stack trace"

**Comment by kitrady** [comment]
I will work on this
