### ISSUE TITLE
Allow for configuration of start up and shut down messages

### ISSUE THREAD

**Issue by laurenassour** [aquanauts/alogamous#8]
Our services have clearly defined start up log messages - make these configuration in alogamous to give clear start/stop criteria if they're all contained in the same log file (like ours are).

**Comment by kitrady** [comment]
I'm a little confused on the phrasing here - to who and why are we giving "clear start/stop criteria"?

**Comment by laurenassour** [comment]
Very fair! In the software I manage, on start up we publish very specific messages that denote that it is starting up:
ex: 
```
====================================================
STARTING Tracking service
    Start time: 2024-06-20 09:00:00.001550+00:00
    Version: 2729a
    Command line: ['.venv/bin/python3', '-m', 'app.tracking_service', '--market', 'US', '--version', '2729a']
====================================================
```

We don't publish anything for shutdown, but I could see a case where someone might. So, alogamous should be able to take configuration that defines what a startup looks like and what a shut down looks like, to help it track starts/stops of a process.

**Comment by kitrady** [comment]
I am working on a parser that will take a log line as a string and turn it into a dictionary so analyzers can access data more precisely. However, it will need to do something when it encounters lines that aren't standard log lines, such as start up messages, so I am going to add some level of configuration for different startup messages
