### ISSUE TITLE
Flag messages that do not conform to log line format

### ISSUE THREAD

**Issue by laurenassour** [aquanauts/alogamous#9]
Ignore stack traces, but otherwise it's probably a print statement that we don't want in there.

**Comment by kitrady** [comment]
I am working on a parser that will take a log line as a string and turn it into a dictionary so analyzers can access data more precisely; this means I will need to define what happens when lines aren't the format that is expected, so I am kinda working on this.

**Comment by kitrady** [comment]
I will work on this
